run-name: grap
on:
  workflow_dispatch: {}
  push:
    branches:
      - main
jobs:
  get_data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Repo Visualizer
        uses: githubocto/repo-visualizer@0.9.1
        with:
          output_file: "diagram.svg"
          root_path: "app/"
          excluded_paths: "dist,node_modules"
      - name: Update diagram
        id: make_diagram
        uses: githubocto/repo-visualizer@0.9.1
        with:
          output_file: "output-diagram.svg"
          artifact_name: "my-diagram"
      - name: Get artifact
        uses: actions/download-artifact@v3
        with:         
          name: "my-diagram"
          path: "downloads"  