run-name: grap
on:
  workflow_dispatch: {}
  push:
    branches:
      - main
jobs:
  get_data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Repo Visualizer
        uses: githubocto/repo-visualizer@0.9.1
        with:
          output_file: "images/diagram.svg"
